policies:
- type: commit
  spec:
    header:
      case: lower
      invalidLastCharacters: .
    body:
      required: true
    dco: true
    maximumOfOneCommit: true
    conventional:
      types:
      - type
      scopes:
      - scope
      descriptionLength: 72
- type: license
  spec:
    skipPaths:
    - .git/
    - .build*/
    includeSuffixes:
    - .ext
    excludeSuffixes:
    - .exclude-ext-prefix.ext
    allowPrecedingComments: false
    header: |
      This is the contents of a license header.
