# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --indent
    - '2'
ci:
  autofix_commit_msg: |
    chore(pre-commit.ci) auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: chore(pre-commit.ci) pre-commit autoupdate
  autoupdate_schedule: weekly
  skip: []
  submodules: false
